### ISSUE TITLE
Dont create shortcut icon 

### ISSUE THREAD

**Issue by mdjacksparrow** [KrishnaMoorthy12/trident#21]
We can't open the editor as directly!
When I am open it go to the terminal and type some commands then after it will be open!
This was reduced the user experience so u will be fix it can directly open by clicking the icon.
Now it will open WinRAR and it's not comfortable!

Then,
i want another specification this is when I am open a new window inside the editor which position is the top left corner of the desktop so this looks like not comfortable!

Then, 
Final one the compiler and running command window are open by separately this leads to don't like that which means noise.
So when I am compiling and also run my program both are open in the same console look like better!

Kindly said to suggestion not for compiling so fixed it! 

Thank you

**Comment by krissh-codes** [comment]
### Hi Jack!
I'm happy to hear from you. 
1. You can open Trident directly using either the jar file attached with releases. In case of stable releases, you can install Trident to your system as well, which creates shortcuts in your desktop as well as in your start menu, so that it'll be comfortable for the users. Check them out. I do not recommend you downloading the source code for testing/ using purposes. Download only the executable assets/ follow the installation instructions if you just wanna use it.

**Comment by krissh-codes** [comment]
2. Yes, I did notice that the application opens on the top left corner of the screen, which is obviously quite annoying and uncomfortable. I'm searching for a solution. Thanks for reporting.

**Comment by krissh-codes** [comment]
3. The compile and run commands are kept seperate only for the user's convenience, so that it'll be easier for the user to keep track and get rid of any errors.

**Comment by krissh-codes** [comment]
I respect every suggestion. Please keep giving your suggestions/ posting issues. Thank you for your valuable contribution. I'll try to add compile and run in same window as a different option in the Tools Menu.

**Comment by mdjacksparrow** [comment]
your says is right but when compile everytime it will be open new window so i am close my previous window in each time so i am asking when open only two console for either compile and run it will be better i think anyway thank u for your response

**Comment by krissh-codes** [comment]
Will see of it's possible..

**Comment by krissh-codes** [comment]
Dear **Jack**, your request for exit after compile and run has been processed. The requested feature will be available in next release.
Thank you for your valuable suggestion.

**Comment by krissh-codes** [comment]
Dear Jack, your requested feature, center positioning of Windows has been added to the source. Will be available from next release. Thank you for your recommendation.
